---
title: "Data Acquisition"
author: "Kayenat Farheen"
---
#This is the second challlenge
::: callout-note

:::

```{r}
library(keyring)
library(dplyr)
library(RSQLite)
library(DBI)
library(httr)
library(glue)
library(jsonlite)
library(xopen)
library(rvest)     # HTML Hacking & Web Scraping
library(tidyverse)
library(stringi) 
library(tibble)
library(rstudioapi)
```

#First Part of the Challenge
# Setting the URL 
```{r}
url <-("https://api.weather.gov/gridpoints/TOP/31,80/forecast")
response=GET(url, query = list(apikey     = Sys.getenv('username'))
)#Somehow it says Rstudio not running when I use API key & ask for password

rawToChar(response$content)
new_table=response %>% 
  .$content %>% 
  rawToChar() %>%
  fromJSON()
```
Printing the table

```{r}
new_table
```
02nd part of the challenge
```{r}
url_home          <- "https://www.radon-bikes.de/"
xopen(url_home) 
html_home         <- read_html(url_home)
bike_family_tbl <- html_home %>%
  html_nodes(css = ".megamenu__item > a") %>%
  html_attr('href') %>%  discard(.p = ~stringr::str_detect(.x,"wear")) %>%
  
  enframe(name = "position", value = "category") %>%
  
  # Add a hashtag so we can get nodes of the categories by id (#)
  mutate(
    family_id = str_glue("https://www.radon-bikes.de/{category}bikegrid")
  )

bike_family_tbl
glimpse(bike_family_tbl$family_id)#Shows 9 categories are there
bike_cat_url=bike_family_tbl$family_id[5]#selecting the fifth category
xopen(bike_cat_url) 
html_bike_cat<- read_html(bike_cat_url)

bike_cat_tbl <- html_bike_cat %>%
  html_nodes(css = ".m-bikegrid__info .a-heading--small") %>% html_text() %>% 
    discard(.p = ~stringr::str_detect(.x,"WMN|WOMEN|GEAR|OUTLET")) %>%
  
  enframe(name = "position", value = "family_class") %>%
  
  # Add a hashtag so we can get nodes of the categories by id (#)
  mutate(
    family_id = str_glue("#{family_class}")
  )
bike_cat_tbl
bike_name_tbl        <- html_bike_cat %>%
  html_nodes(css = ".m-bikegrid__info .a-heading--small") %>%
  html_text() %>% enframe(name = "position", value = "bike_name")

```

```{r}
bike_price_tbl=html_bike_cat %>%
  html_nodes(css = ".m-bikegrid__price.currency_eur .m-bikegrid__price--active") %>% html_text() %>% 
  
  enframe(name = "position", value = "price")
bike_price_tbl  
total_bikes_and_price_tbl=full_join(bike_name_tbl,bike_price_tbl)

bike_name_and_price_tbl=total_bikes_and_price_tbl %>% select(bike_name,price)
bike_name_and_price_tbl$price
bike_name_and_price_tbl=bike_name_and_price_tbl%>% mutate(price=str_remove_all(price,"€"))#Removing Euro sign
bike_name_and_price_tbl$price=as.numeric(bike_name_and_price_tbl$price)#Converting from string to numeric
bike_name_and_price_tbl$price
bike_name_and_price_tbl=bike_name_and_price_tbl%>% 
  mutate(across(where(is.character), str_trim))#Removing unnecessary spaces from bike name column
bike_name_and_price_tbl
range(bike_name_and_price_tbl$price)#Seems like a reasonable range of price

```

